### ISSUE TITLE
event.message.sender.username is not None:

### ISSUE THREAD

**Issue by brokechubb** [UrekD/Telegram-To-Discord#14]
```
Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/telethon/client/updates.py", line 497, in _dispatch_update
    await callback(event)
  File "//main.py", line 72, in handler
    if event.message.sender.username is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'username'
```

This happens when I run in in a venv and also in a docker image.... I am on debian sid

Thank you

**Comment by UrekD** [comment]
Hello,

It looks like the sender has no username could be chat related since I'm not sure how everything works. If it's not something you wish to have just use the second condition.

**Comment by UrekD** [comment]
Closing due to inactivity...
